# https://travis-ci.com/kecnry/distl

language: python

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

dist: bionic

env:
    global:
        # Set defaults to avoid repeating in most cases
        - PIP_DEPENDENCIES='nose codecov'
        - PYTHON_VERSION=3.6

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        - os: linux
          env: PYTHON_VERSION=3.6

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py build
    - python setup.py install --user

script:
    - cd tests;
    - nosetests --with-coverage --cover-package=crimpl -v -s -d;

after_success:
    - codecov
