site_name: crimpl
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
repo_name: GitHub
repo_url: https://github.com/kecnry/crimpl/
edit_uri: blob/main/docs/
extra_css: [extra.css]
nav:
    - Installation & Setup: index.md
    - Server Implementations:
        - LocalThread: LocalThread.md
        - RemoteThread: RemoteThread.md
        - RemoteSlurm: RemoteSlurm.md
        - RemotePBS: RemotePBS.md
        - AWSEC2: AWSEC2.md
    - API:
        - crimpl (top-level): api/crimpl.md
        - LocalThreadServer: api/LocalThreadServer.md
        - LocalThreadJob: api/LocalThreadJob.md
        - RemoteThreadServer: api/RemoteThreadServer.md
        - RemoteThreadJob: api/RemoteThreadJob.md
        - RemoteSlurmServer: api/RemoteSlurmServer.md
        - RemoteSlurmJob: api/RemoteSlurmJob.md
        - RemotePBSServer: api/RemotePBSServer.md
        - RemotePBSJob: api/RemotePBSJob.md
        - AWSEC2Server: api/AWSEC2Server.md
        - AWSEC2Job: api/AWSEC2Job.md
