# This workflow will install dependencies and run nosetests on pushes to all branches
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7]
        os: [ubuntu-latest] # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

    name: ${{ matrix.os }} python${{ matrix.python-version}}
    steps:
    - name: Checkout crimpl
      uses: actions/checkout@v2

    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: MacOS Xcode setup
      if: matrix.os == 'macOS-10.15'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: MacOS Setup # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
      if: matrix.os == 'macOS-10.15'
      run: |
        export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

    - name: Install from source
      run: |
        python setup.py build && python setup.py install --user

    - name: Run nosetests
      run: |
        nosetests --with-coverage --cover-package=crimpl -v -s -d;
